### ISSUE TITLE
Redux: AttributeError: 'Theme' object has no attribute 'name'

### ISSUE THREAD

**Issue by WritingSolutions2020** [hfagerlund/mkdocs-docskimmer#14]
See also closed issue number 13, ['Theme' object has no attribute 'name'](https://github.com/hfagerlund/mkdocs-docskimmer/issues/13). Per the following, I implemented the "fix" for that issue (set `name` to `null`) yet I continue to have the problem. (I added a comment to that closed issue but wasn't sure that would be noticed. So I'm creating a new issue here...)

### Summary

For Python 3.5.2, GCC 5.4.0 20160609, `mkdocs --version` == `1.0.4`, `mkdocs-docskimmer` directory at the same level as the project's `docs` folder. Along the way I stopped then restarted the `mkdocs serve &` process.

I'm having the problem described above even though my MkDocs project's `mkdocs.yml` file includes `name: null`.

------
### The complete trace
```
[I 190124 15:36:10 watcher:92] Running task: <function serve.<locals>.builder at 0xb70d05cc> (delay: None)
INFO    -  Building documentation...
[E 190124 15:36:10 ioloop:801] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/usr/local/lib/python3.5/dist-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python3.5/dist-packages/livereload/watcher.py", line 93, in examine
        func()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/serve.py", line 107, in builder
        site_dir=site_dir
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 197, in load_config
        errors, warnings = cfg.validate()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 115, in validate
        post_failed, post_warnings = self._post_validate()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 95, in _post_validate
        config_option.post_validation(self, key_name=key)
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 430, in post_validation
        format(path=theme_config['custom_dir'], name=self.name))
    AttributeError: 'Theme' object has no attribute 'name'
```
------

------
### The _mkdocs.yml_ file:

```
site_name: MkDocs Demo

nav:
  - Intro: index.md
  - Setup: setup.md
  - Style: style.md
  - Run / Build: build.md
  - Links: links.md

theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ["search"]

# add theme version number here
extra:
  version: 0.4.x
```
------

+ IF I cut the `theme`, `plugins`, and `extra` sections out of the `mkdocs.yml` file, THEN it builds without error.

+ IF I paste those sections back into the file, THEN as shown above, the last line of the build process ==   `AttributeError: 'Theme' object has no attribute 'name'`

**Comment by hfagerlund** [comment]
@WritingSolutions2020 -

Thanks for moving this into its own issue, and for trying the theme.

The steps/setup that you describe seem fine.

I tested the theme with MkDocs v1.0.4 using (only) Python v2.7.14 so far, and do not encounter any build errors using the `mkdocs.yml` file that you provided... so this *may* be a Python version issue(?) but I cannot say for sure without taking a closer look as soon as I have time.

**Comment by hfagerlund** [comment]
@WritingSolutions2020 -

I switched to testing with Python v3.6, but have been unable to re-create the build error that you are seeing.

Have you tried the following:
* stop the local server (I notice `watcher` is mentioned in your trace)
* then run `$ rm -rf site` from the root directory (this ensures that *all* previous changes are removed - ie. new changes are not just added 'on top' of them)
* re-run the build: `$ mkdocs build`
* restart the server.

(Please let me know whether the above workflow affects the issue.)

> IF I cut the theme, plugins, and extra sections out of the mkdocs.yml file, THEN it builds without error.

Without the `theme` section, the site uses `mkdocs` - one of the two 'installed'/built-in themes. Disabling/enabling the `search` plugin did not have any effect on the build (in my testing).

Maybe `$ mkdocs build -v` can provide some more/helpful debug info?

**Comment by hfagerlund** [comment]
> For Python 3.5.2, GCC 5.4.0 20160609

It appears MkDocs [supports Python v3.5](https://pypi.org/project/mkdocs/).

**Comment by WritingSolutions2020** [comment]
Thanks. I tried those steps plus some others. They didn't work -- the site can't be built if the theme's sections are in the YAML file.

I'm deleting the theme and moving on -- I'll let you know if I find time to perform additional troubleshooting some day...

Cheers & thanks 'gain...

**Comment by WritingSolutions2020** [comment]
@hfagerlund I finally got the theme to work. And encountered some small errors along the way. The following information may be useful to others...?

### ONE

Because I'm a newcomer to MkDocs I may have misunderstood how themes are intended to work. I supposed (uh oh) that one could use a theme to revise the presentation of an existing MkDocs project / site. But after numerous attempts to do that I moved on to _TWO_, below.

### TWO

I created a new top-level directory and un-zip'ed the _docskimmer_ theme into that directory as follows:

------
```
total 40

CHANGELOG.md
docs
LICENSE
MANIFEST.in
mkdocs_docskimmer
mkdocs.yml
README.md
screenshots
setup.py
site
```
------

### THREE

In that directory, in the BASH command line I ran `mkdocs build`.

**RESULT:** MkDocs reported the following errors:

1. In _mkdocs.yml_, the path specs to content in the _docs_ required me to prefix the pathnames with `/`. This is my now-working _nav_ section: 

```
nav:
    - Intro: /index.md
    - Examples:
        - Sample1: /examples/sample-page.md
        - Sample2: /examples/another-sample-page.md
```
If, to give one example, I remove the `/` character from in front of the `index.md` file name, I receive:

> WARNING -  A relative path to 'index.md' is included in the 'nav' configuration, which is not found in the documentation files

I'm not sure why this is the case: My other MkDocs project's YML file does not require me to begin the path names with `/`...

2. In `docs/examples`, the Markdown files `sample-page` and `another-sample-page` needed to have the `.md` filename extension appended to the file names. 

### FOUR

After making those changes the _docskimmer_ built without errors. I then ran `mkdocs serve &` to inspect the site's pages.

From here I'll move my content pages into the site's _docs_ folder and for forward from there.

Cheers & hope this helps...

**Comment by WritingSolutions2020** [comment]
I'll add that even though the theme seems to be more or less working, I'm regularly encountering _404_ errors after serve-ing or build-ing. I'll try working through those. One thing I've noticed is that in the _nav_ section the - _Intro:_ and _Examples:_ pairs were indented FOUR spaces rather than TWO. I may well be wrong, but does not YAML require TWO spaces...?

**Comment by WritingSolutions2020** [comment]
Even though the main page of the site displays after serve-ing, it appears that the site isn't being built properly. I'll mess around with this when I find time. But overall, after performing the steps given in my preceding comment, I'm having problems getting the them to work "cleanly"...

**Comment by hfagerlund** [comment]
@WritingSolutions2020 -

Glad to hear its working for you - thanks for letting me know. Here are a few hopefully helpful hints:

## RE: point 'One' -

docSkimmer is a *standalone* theme which may be used on its own as a complete (minimal) theme, or may be customized.

To [override some of the styles](https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme) in docSkimmer (or another) theme, use the `extra` section in `mkdocs.yml` to add custom stylesheets to the site.

## RE: points 'Two' and 'Four' -

This directory structure looks good. The bare minimum requirements are:

* `/docs`  - replace the contents of this directory with your own content `.md` files;
* `MANIFEST.in` and `setup.py` - required for installing docSkimmer theme;
* `/mkdocs_docskimmer` - required for docSkimmer theme;
* `mkdocs.yml` - customize this as per [your project's requirements](https://www.mkdocs.org/#adding-pages) and the versions of MkDocs and [docSkimmer](https://github.com/hfagerlund/mkdocs-docskimmer#usage) that you are using;
* `/site` - may be safely removed; this directory is automatically (re)generated by MkDocs when build commands are run.

## RE: point 'Three' -

Relative path warnings were added in [MkDocs v1.0.3](https://www.mkdocs.org/about/release-notes/#version-103-2018-08-29), and do not affect the functionality of docSkimmer theme (ie. they are not errors, and do not break the build).

----
There is quite a bit of good documentation about [MkDocs](https://www.mkdocs.org/#getting-started) out there, but thanks for giving me some ideas for how I might enhance the theme's usage instructions.
