### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by mauriciobaeza** [hfagerlund/mkdocs-docskimmer#15]
How to syntax highlighting code with this theme?

Thanks in advance

**Comment by hfagerlund** [comment]
@mauriciobaeza -
Thanks for the question.

Although docSkimmer does not add syntax highlighting out-of-the-box, it works with any JavaScript syntax highlighter library that is added using the [`extra_javascript` configuration option](https://www.mkdocs.org/user-guide/configuration/#extra_javascript) in 'mkdocs.yml'.

Follow these steps to add [highlight.js](https://github.com/highlightjs/highlight.js):
* Create a `/js` subdirectory under your project's `/docs` directory;
* [Download (and unzip) highlight.js](https://highlightjs.org/download/) into your project's `/docs/js` (sub)directory;
* Create a custom script in `/docs/js` (for this example, it will be called 'load-highlight.js') containing the following code:
```
hljs.initHighlightingOnLoad();
```
* Move the highlight.js `/styles` directory out of your project's `/docs/js` dir, into its own subdirectory under `/docs` (for this example, it will be renamed to `/docs/styles-from-highlightjs`);
* Add the following to your project's `mkdocs.yml` file:
```
extra_javascript:
  - js/highlight.pack.js
  - js/load-highlight.js
extra_css:
  - styles-from-highlightjs/default.css
```
* Add some (test) code blocks to any '.md' file in the `/docs` dir:

A sample code block:
```html
<!-- testing HTML code highlighting -->
<title>Test Title</title>
```

Another sample code block:
```python
"""A little bit of Python code."""
def foo():
    bar = Bar()
    return None    
```
* Rebuild your project:
```
$ mkdocs build --clean
```

Hope this helps.

**Comment by mauriciobaeza** [comment]
Very thanks, work fine.

**Comment by hfagerlund** [comment]
Happy to hear that it's working for you. Thanks for letting me know.
