### ISSUE TITLE
ERROR   -  Config value 'theme': The theme 'docskimmer' does not appear to have a configuration file.

### ISSUE THREAD

**Issue by pawamoy** [hfagerlund/mkdocs-docskimmer#17]
Hello, is this theme still maintained?

I'm building a [gallery of MkDocs themes](https://pawamoy.github.io/mkdocs-gallery/) and am getting this error when building:

```
ERROR   -  Config value 'theme': The theme 'docskimmer' does not appear to have a configuration file. Please upgrade to a current version of the theme.

Aborted with 1 configuration errors!
```

**Comment by hfagerlund** [comment]
@pawamoy -

The [latest version of this theme (v0.4.0)](https://github.com/hfagerlund/mkdocs-docskimmer#version-compatibility) was tested with [MkDocs version 1.0.4](https://www.mkdocs.org/about/release-notes/#version-104-2018-09-07). 
(The [latest release of MkDocs at the time of writing](https://github.com/mkdocs/mkdocs/releases/tag/1.5.3) is v1.5.3.)

I will try to take a look, but if you find the time before I do, please feel free to [make a contribution to the docSkimmer theme project](https://github.com/hfagerlund/mkdocs-docskimmer/fork). Thanks.

**Comment by pawamoy** [comment]
Thank you! My plate is a little full right now, so I will probably not contribute any time soon. I was mainly reporting to see if something could be done, or if I should remove the theme from the gallery :slightly_smiling_face: For now I've removed it (since it doesn't build at all), but if you get it working again for latest MkDocs version, let me know and I'll reinclude it immediately :slightly_smiling_face:

**Comment by hfagerlund** [comment]
@pawamoy -

Thanks for letting me know that it doesn't build with v1.5.3.

Without investigating the [changes to MkDocs since 2018](https://www.mkdocs.org/about/release-notes/) (when the latest version of this theme was released), it is impossible to say whether this issue could be remedied with a simple configuration change, or if it is a request for a new version of the theme.
